package com.data_management;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 * Reads patient health data from text files within a specified directory.
 * <p>
 * This class implements the {@link DataReader} interface. It scans a target directory 
 * for files generated by the HealthDataSimulator, reads each file line-by-line, parses 
 * the comma-separated values, and loads the structured data into the provided {@link DataStorage}.
 */
public class FileDataReader implements DataReader {

    private String outputDirectoryPath;

    /**
     * Constructs a new FileDataReader.
     *
     * @param outputDirectoryPath The path to the directory containing the simulator's output files.
     */
    public FileDataReader(String outputDirectoryPath) {
        this.outputDirectoryPath = outputDirectoryPath;
    }

    /**
     * Reads all data files from the specified directory and stores the parsed records into DataStorage.
     * <p>
     * Expected line format: "PatientId, Timestamp, Label, Data" 
     * Example: "1, 1700000000000, HeartRate, 75.0" or "2, 1700000000000, Saturation, 98.0%"
     *
     * @param dataStorage The central storage system where the parsed patient data will be saved.
     * @throws IOException If the directory does not exist, or if an error occurs while reading a file.
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        File directory = new File(outputDirectoryPath);

        // Check if the directory actually exists and is a folder
        if (!directory.exists() || !directory.isDirectory()) {
            throw new IOException("The specified directory does not exist or is not a directory: " + outputDirectoryPath);
        }

        // Get a list of all files inside the directory
        File[] files = directory.listFiles();
        if (files == null || files.length == 0) {
            System.out.println("No data files found in the directory: " + outputDirectoryPath);
            return;
        }

        // Loop through every file found in the directory
        for (File file : files) {
            // Only attempt to read standard files (ignore sub-folders or hidden system files)
            if (file.isFile() && !file.isHidden()) {
                parseFile(file, dataStorage);
            }
        }
    }

    /**
     * Helper method to parse a single file line-by-line.
     * * @param file        The specific file being read.
     * @param dataStorage The storage system to push the data into.
     * @throws IOException If there is an issue reading the file's contents.
     */
    private void parseFile(File file, DataStorage dataStorage) throws IOException {
        // BufferedReader efficiently reads text from a character-input stream
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            
            // Read until we hit the end of the file
            while ((line = br.readLine()) != null) {
                try {
                    // Split the line by commas. Expected parts: [ID, Time, Label, Value]
                    String[] parts = line.split(",");
                    
                    if (parts.length == 4) {
                        int patientId = Integer.parseInt(parts[0].trim());
                        long timestamp = Long.parseLong(parts[1].trim());
                        String label = parts[2].trim();
                        
                        // Some data (like blood saturation) might have a '%' sign. 
                        // We use a regex replaceAll to strip out any non-numeric characters before parsing.
                        String rawValue = parts[3].replaceAll("[^\\d.]", "").trim();
                        double value = Double.parseDouble(rawValue);

                        // Push the clean, parsed data into the storage system
                        dataStorage.addPatientData(patientId, value, label, timestamp);
                    }
                } catch (NumberFormatException e) {
                    // If a line is corrupted or has bad numbers, we print a warning but continue reading the file
                    System.err.println("Skipping malformed line in file " + file.getName() + ": " + line);
                }
            }
        }
    }
}